#!/usr/bin/env python3
import argparse
import pandas as pd
import matplotlib.pyplot as plt

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", required=True, help="Path to results.csv generated by exp2.sh")
    ap.add_argument("--out", default="time_comparison.png", help="Output figure filename")
    args = ap.parse_args()

    df = pd.read_csv(args.results)

    df["N"] = df["ex"].astype(int)

    df["sim_time_s"] = df["sim_time_s"].astype(float)
    df["post_time_s"] = df["post_time_s"].astype(float)
    df["workflow_time_s"] = df["sim_time_s"] + df["post_time_s"]

    adhoc = df[df["mode"] == "adhoc"].sort_values("N")
    insitu = df[df["mode"] == "insitu"].sort_values("N")

    plt.figure()
    plt.plot(adhoc["N"], adhoc["sim_time_s"], marker="o", label="Ad-hoc (simulation only)")
    plt.plot(adhoc["N"], adhoc["workflow_time_s"], marker="o", label="Ad-hoc (simulation + postprocess)")
    plt.plot(insitu["N"], insitu["sim_time_s"], marker="o", label="In-situ (simulation, includes stats)")

    plt.xlabel("Mesh size (ex = ey), ez = 1")
    plt.ylabel("Time (s)")
    plt.title("Execution time vs problem size: Ad-hoc vs In-situ")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()
    plt.savefig(args.out, dpi=200)
    print(f"Wrote {args.out}")

if __name__ == "__main__":
    main()