#!/usr/bin/env python3
import argparse
import csv
import os
import matplotlib.pyplot as plt

def read_results(path):
    rows = []
    with open(path, newline="") as f:
        r = csv.DictReader(f)
        for row in r:
            rows.append(row)
    return rows

def to_int(x, default=0):
    try:
        return int(float(x))
    except Exception:
        return default

def to_float(x, default=0.0):
    try:
        return float(x)
    except Exception:
        return default

def group_by_mode(rows):
    adhoc = []
    insitu = []
    for row in rows:
        mode = row.get("mode", "").strip()
        if mode == "adhoc":
            adhoc.append(row)
        elif mode == "insitu":
            insitu.append(row)
    return adhoc, insitu

def sort_by_N(rows):
    return sorted(rows, key=lambda r: to_int(r.get("ex", 0)))

def extract_series(rows):
    N = []
    sim_time = []
    post_time = []
    total_time = []
    bytes_written = []
    for r in rows:
        n = to_int(r.get("ex", 0))
        st = to_float(r.get("sim_time_s", 0.0))
        pt = to_float(r.get("post_time_s", 0.0))
        bw = to_float(r.get("snapshot_size_bytes", 0.0))
        N.append(n)
        sim_time.append(st)
        post_time.append(pt)
        total_time.append(st + pt)
        bytes_written.append(bw)
    return N, sim_time, post_time, total_time, bytes_written

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", required=True, help="Path to results.csv generated by exp2.sh")
    ap.add_argument("--out-time", default="exp2_time_scaling.png", help="Output PNG for time plot")
    ap.add_argument("--out-io", default="exp2_io_scaling.png", help="Output PNG for output-size plot")
    args = ap.parse_args()

    if not os.path.isfile(args.results):
        raise SystemExit(f"Missing file: {args.results}")

    rows = read_results(args.results)
    adhoc_rows, insitu_rows = group_by_mode(rows)

    adhoc_rows = sort_by_N(adhoc_rows)
    insitu_rows = sort_by_N(insitu_rows)

    N_a, sim_a, post_a, total_a, bytes_a = extract_series(adhoc_rows)
    N_i, sim_i, post_i, total_i, bytes_i = extract_series(insitu_rows)

    # ---- Plot 1: time scaling (3 curves) ----
    plt.figure()
    plt.plot(N_i, sim_i, marker="o", label="In-situ (simulation)")
    plt.plot(N_a, sim_a, marker="o", label="Ad-hoc (simulation only)")
    plt.plot(N_a, total_a, marker="o", label="Ad-hoc (simulation + postprocess)")
    plt.xlabel("Problem size (ex = ey), ez = 1")
    plt.ylabel("Time (s)")
    plt.title("Time scaling: In-situ vs Ad-hoc (with/without postprocess)")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()
    plt.savefig(args.out_time, dpi=200)

    # ---- Plot 2: output size scaling (MB) ----
    MB_a = [b / (1024.0 * 1024.0) for b in bytes_a]
    MB_i = [b / (1024.0 * 1024.0) for b in bytes_i]

    plt.figure()
    plt.plot(N_i, MB_i, marker="o", label="In-situ output size (MB)")
    plt.plot(N_a, MB_a, marker="o", label="Ad-hoc snapshots size (MB)")
    plt.xlabel("Problem size (ex = ey), ez = 1")
    plt.ylabel("Data written (MB)")
    plt.title("Output size scaling: Ad-hoc snapshots vs In-situ summary")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()
    plt.savefig(args.out_io, dpi=200)

    print(f"Wrote {args.out_time}")
    print(f"Wrote {args.out_io}")

if __name__ == "__main__":
    main()